<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- saved from url=(0083)https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx -->
<html style="--wm-toolbar-height: 67px;"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><script src="./ROBLOX_files/athena.js.download" type="text/javascript"></script>
<script type="text/javascript">window.addEventListener('DOMContentLoaded',function(){var v=archive_analytics.values;v.service='wb';v.server_name='wwwb-app249.us.archive.org';v.server_ms=791;archive_analytics.send_pageview({});});</script>
<script type="text/javascript" src="./ROBLOX_files/bundle-playback.js.download" charset="utf-8"></script>
<script type="text/javascript" src="./ROBLOX_files/wombat.js.download" charset="utf-8"></script>
<script>window.RufflePlayer=window.RufflePlayer||{};window.RufflePlayer.config={"autoplay":"on","unmuteOverlay":"hidden","showSwfDownload":true};</script>
<script type="text/javascript" src="./ROBLOX_files/ruffle.js.download"></script>
<script type="text/javascript">
    __wm.init("https://web.archive.org/web");
  __wm.wombat("http://www.roblox.com:80/Login/Stealth.aspx","20051126085034","https://web.archive.org/","web","https://web-static.archive.org/_static/",
	      "1132995034");
</script>
<link rel="stylesheet" type="text/css" href="./ROBLOX_files/banner-styles.css">
<link rel="stylesheet" type="text/css" href="./ROBLOX_files/iconochive.css">
<!-- End Wayback Rewrite JS Include -->

		<title>ROBLOX</title>
		<link rel="stylesheet" type="text/css" href="./ROBLOX_files/Roblox.css">
		<meta name="GENERATOR" content="Microsoft Visual Studio .NET 7.1">
		<meta name="CODE_LANGUAGE" content="C#">
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
	</head>
	<body ms_positioning="FlowLayout"><!-- BEGIN WAYBACK TOOLBAR INSERT -->
<script>__wm.rw(0);</script>
<div id="wm-ipp-base" lang="en" style="display: block; direction: ltr; height: 67px;" toolbar-mode="auto"><template shadowrootmode="closed"><div id="wm-ipp" style="position:fixed;left:0;top:0;right:0;">
<div id="donato" style="position:relative;width:100%;height:0;">
  <div id="donato-base">
    <iframe id="donato-if" src="https://archive.org/includes/donate.php?as_page=1&amp;platform=wb&amp;referer=https%3A//web.archive.org/web/20051126085034/http%3A//www.roblox.com/Login/Stealth.aspx" scrolling="no" frameborder="0" style="width:100%; height:100%">
    </iframe>
  </div>
</div><div id="wm-ipp-inside">
  <div id="wm-toolbar" style="position:relative;display:flex;flex-flow:row nowrap;justify-content:space-between;" nav="async">
    <div id="wm-logo" style="/*width:110px;*/padding-top:12px;">
      <a href="https://web.archive.org/web/" title="Wayback Machine home page"><img src="https://web-static.archive.org/_static/images/toolbar/wayback-toolbar-logo-200.png" srcset="https://web-static.archive.org/_static/images/toolbar/wayback-toolbar-logo-100.png, https://web-static.archive.org/_static/images/toolbar/wayback-toolbar-logo-150.png 1.5x, https://web-static.archive.org/_static/images/toolbar/wayback-toolbar-logo-200.png 2x" alt="Wayback Machine" style="width:100px" border="0"></a>
    </div>
    <div class="c" style="display:flex;flex-flow:column nowrap;justify-content:space-between;flex:1;">
      <form class="u" style="display:flex;flex-direction:row;flex-wrap:nowrap;" target="_top" method="get" action="https://web.archive.org/web/submit" name="wmtb" id="wmtb"><input type="text" name="url" id="wmtbURL" value="http://www.roblox.com/Login/Stealth.aspx" onfocus="this.focus();this.select();" style="flex:1;" autocomplete="off"><input type="hidden" name="type" value="replay"><input type="hidden" name="date" value="20051126085034"><input type="submit" value="Go">
      </form>
      <div style="display:flex;flex-flow:row nowrap;align-items:flex-end;">
                <div class="s" id="wm-nav-captures" style="flex:1;"><a class="t" href="https://web.archive.org/web/*/http://www.roblox.com/Login/Stealth.aspx" title="See a list of every capture for this URL">78 captures</a><div class="r" title="Timespan for captures of this URL">26 Nov 2005 - 3 May 2026</div></div>
        <div class="k">
          <a href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx" id="wm-graph-anchor">
            <div id="wm-ipp-sparkline" title="Explore captures for this URL" style="position: relative">
              <canvas id="wm-sparkline-canvas" width="775" height="27" border="0"></canvas>
            <div class="yt" style="display: none; width: 25px; height: 27px;"></div><div class="mt" style="display: none; width: 2px; height: 27px;"></div></div>
          </a>
        </div>
      </div>
    </div>
    <div class="n">
      <table>
        <tbody>
          <!-- NEXT/PREV MONTH NAV AND MONTH INDICATOR -->
          <tr class="m">
            <td class="b" nowrap="nowrap">Oct</td>
            <td class="c" id="displayMonthEl" title="You are here: 08:50:34 Nov 26, 2005">NOV</td>
            <td class="f" nowrap="nowrap"><a href="https://web.archive.org/web/20060110164903/http://www.roblox.com/Login/Stealth.aspx" title="16:49:03 Jan 10, 2006">Jan</a></td>
          </tr>
          <!-- NEXT/PREV CAPTURE NAV AND DAY OF MONTH INDICATOR -->
          <tr class="d">
            <td class="b" nowrap="nowrap"><span class="ta"></span></td>
            <td class="c" id="displayDayEl" style="width:34px;font-size:22px;white-space:nowrap;" title="You are here: 08:50:34 Nov 26, 2005">26</td>
            <td class="f" nowrap="nowrap"><a href="https://web.archive.org/web/20060110164903/http://www.roblox.com/Login/Stealth.aspx" title="16:49:03 Jan 10, 2006"><span class="ta"></span></a></td>
          </tr>
          <!-- NEXT/PREV YEAR NAV AND YEAR INDICATOR -->
          <tr class="y">
            <td class="b" nowrap="nowrap">2004</td>
            <td class="c" id="displayYearEl" title="You are here: 08:50:34 Nov 26, 2005">2005</td>
            <td class="f" nowrap="nowrap"><a href="https://web.archive.org/web/20110611005610/http://www.roblox.com/Login/Stealth.aspx" title="00:56:10 Jun 11, 2011">2011</a></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="r" style="display:flex;flex-flow:column nowrap;align-items:flex-end;justify-content:space-between;">
      <div id="wm-btns" style="text-align:right;height:23px;">
                <span class="xxs">
          <div id="wm-save-snapshot-success">success</div>
          <div id="wm-save-snapshot-fail">fail</div>
          <a id="wm-save-snapshot-open" href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx#" title="Share via My Web Archive" style="display: inline-block;">
            <span class="iconochive-web"></span>
          </a>
          <a href="https://archive.org/account/login.php" title="Sign In" id="wm-sign-in" style="display: none;">
            <span class="iconochive-person"></span>
          </a>
          <span id="wm-save-snapshot-in-progress" class="iconochive-web"></span>
        </span>
                <a class="xxs" href="https://help.archive.org/help/category/the-wayback-machine/" title="Get some help using the Wayback Machine" style="top:-6px;"><span class="iconochive-question" style="color:rgb(87,186,244);font-size:160%;"></span></a>
        <a id="wm-tb-close" href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx#close" style="top:-2px;" title="Close the toolbar"><span class="iconochive-remove-circle" style="color:#888888;font-size:240%;"></span></a>
      </div>
      <div id="wm-share" class="xxs">
        <a href="https://web.archive.org/web/20051126085034/http://web.archive.org/screenshot/http://www.roblox.com/Login/Stealth.aspx" id="wm-screenshot" title="screenshot" style="visibility: hidden;">
          <span class="wm-icon-screen-shot"></span>
        </a>
        <a href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx#" id="wm-video" title="video">
          <span class="iconochive-movies"></span>
        </a>
        <a id="wm-share-facebook" href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx#" data-url="https://web.archive.org/web/20051126085034/http://www.roblox.com:80/Login/Stealth.aspx" title="Share on Facebook" style="margin-right:5px;" target="_blank"><span class="iconochive-facebook" style="color:#3b5998;font-size:160%;"></span></a>
        <a id="wm-share-twitter" href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx#" data-url="https://web.archive.org/web/20051126085034/http://www.roblox.com:80/Login/Stealth.aspx" title="Share on Twitter" style="margin-right:5px;" target="_blank"><span class="iconochive-twitter" style="color:#1dcaff;font-size:160%;"></span></a>
      </div>
      <div style="padding-right:2px;text-align:right;white-space:nowrap;">
        <a id="wm-expand" class="wm-btn wm-closed" href="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx#expand"><span id="wm-expand-icon" class="iconochive-down-solid"></span> <span class="xxs" style="font-size:80%;">About this capture</span></a>
      </div>
    </div>
  </div>
    <div id="wm-capinfo" style="border-top:1px solid #777;display:none; overflow: hidden">
        <div id="wm-capinfo-notice" source="api"></div>
                <div id="wm-capinfo-collected-by">
    <div style="background-color:#666;color:#fff;font-weight:bold;text-align:center;padding:2px 0;">COLLECTED BY</div>
    <div style="padding:3px;position:relative" id="wm-collected-by-content">
            <div style="display:inline-block;vertical-align:top;width:50%;">
			<span class="c-logo" style="background-image:url(https://archive.org/services/img/alexacrawls);"></span>
		Organization: <a style="color:#33f;" href="https://archive.org/details/alexacrawls" target="_new"><span class="wm-title">Alexa Crawls</span></a>
		<div style="max-height:75px;overflow:hidden;position:relative;">
	  <div style="position:absolute;top:0;left:0;width:100%;height:75px;background:linear-gradient(to bottom,rgba(255,255,255,0) 0%,rgba(255,255,255,0) 90%,rgba(255,255,255,255) 100%);"></div>
	  Starting in 1996, <a href="http://www.alexa.com/">Alexa Internet</a> has been donating their crawl data to the Internet Archive.  Flowing in every day, these data are added to the <a href="http://web.archive.org/">Wayback Machine</a> after an embargo period.
	</div>
	      </div>
      <div style="display:inline-block;vertical-align:top;width:49%;">
			<span class="c-logo" style="background-image:url(https://archive.org/services/img/alexa_ef)"></span>
		<div>Collection: <a style="color:#33f;" href="https://archive.org/details/alexa_ef" target="_new"><span class="wm-title">Alexa Crawl EF</span></a></div>
		<div style="max-height:75px;overflow:hidden;position:relative;">
	  <div style="position:absolute;top:0;left:0;width:100%;height:75px;background:linear-gradient(to bottom,rgba(255,255,255,0) 0%,rgba(255,255,255,0) 90%,rgba(255,255,255,255) 100%);"></div>
	  Crawl EF from Alexa Internet.  This data is currently not publicly accessible.
	</div>
	      </div>
    </div>
    </div>
    <div id="wm-capinfo-timestamps">
    <div style="background-color:#666;color:#fff;font-weight:bold;text-align:center;padding:2px 0;" title="Timestamps for the elements of this page">TIMESTAMPS</div>
    <div>
      <div id="wm-capresources" style="margin:0 5px 5px 5px;max-height:250px;overflow-y:scroll !important"></div>
      <div id="wm-capresources-loading" style="text-align:left;margin:0 20px 5px 5px;display:none"><img src="https://web-static.archive.org/_static/images/loading.gif" alt="loading"></div>
    </div>
    </div>
  </div></div></div><link rel="stylesheet" type="text/css" href="./ROBLOX_files/banner-styles.css"><link rel="stylesheet" type="text/css" href="./ROBLOX_files/iconochive.css"><div class="wb-autocomplete-suggestions "></div></template>
</div><div id="wm-ipp-print">The Wayback Machine - https://web.archive.org/web/20051126085034/http://www.roblox.com:80/Login/Stealth.aspx</div>
<script type="text/javascript">//<![CDATA[
__wm.bt(775,27,25,2,"web","http://www.roblox.com/Login/Stealth.aspx","20051126085034",1996,"https://web-static.archive.org/_static/",["https://web-static.archive.org/_static/css/banner-styles.css?v=1utQkbB3","https://web-static.archive.org/_static/css/iconochive.css?v=3PDvdIFv"], false);
  __wm.rw(1);
//]]></script>
<!-- END WAYBACK TOOLBAR INSERT -->
 
		<form name="Form1" method="post" action="https://web.archive.org/web/20051126085034/http://www.roblox.com/Login/Stealth.aspx" id="Form1">
<input type="hidden" name="__EVENTTARGET" value="">
<input type="hidden" name="__EVENTARGUMENT" value="">
<input type="hidden" name="__VIEWSTATE" value="dDwtMTYyNjQ0OTE5OztsPExvZ2luMTpDaGVja0JveFJlbWVtYmVyTWU7Pj5CrdLKNBTnIzJzHIAaJPqWKymWTw==">

<script language="javascript" type="text/javascript">
<!--
	function __doPostBack(eventTarget, eventArgument) {
		var theform;
		if (window.navigator.appName.toLowerCase().indexOf("microsoft") > -1) {
			theform = document.Form1;
		}
		else {
			theform = document.forms["Form1"];
		}
		theform.__EVENTTARGET.value = eventTarget.split("$").join(":");
		theform.__EVENTARGUMENT.value = eventArgument;
		theform.submit();
	}
// -->
</script>

			<div align="center">
				<table cellspacing="10">
					<tbody><tr>
						<td align="center">
							<p><img src="./ROBLOX_files/roblox_logo.PNG"></p>
							<table width="340" align="center">
								<tbody><tr>
									<td align="left" width="100%" bgcolor="aliceblue" style="PADDING-RIGHT: 1em; PADDING-LEFT: 1em; PADDING-BOTTOM: 1em; PADDING-TOP: 1em"><br>
										<p>Dear ROBLOX users:
										</p>
										<p>We’ve completed our beta 1.0 period – <strong>thank you for your input!</strong> 
											We’re working on a brand new version of ROBLOX with lots of new features.
										</p>
										<p>In the meantime, access to the website is&nbsp;restricted.
										</p>
										<p>Existing users can still sign on here, however no new user accounts can be 
											created at this time.
										</p>
										<p>If you'd like us to notify you when we go live again, then <a href="https://web.archive.org/web/20051126085034/mailto:info@roblox.com">
												contact us</a>.
										</p>
										<p>Thanks,
										</p>
										<p>The ROBLOX team
										</p>
									</td>
								</tr>
							</tbody></table>
							<p><img src="./ROBLOX_files/Model.jpg"></p>
						</td>
						<td><p>
								
<table id="Table1">
	<tbody><tr>
		<td>Username or E-mail:</td>
		<td width="140">
			<input name="Login1:UserName" type="text" id="Login1_UserName"></td>
		<td>
			
			</td>
	</tr>
	<tr>
		<td>Password:</td>
		<td width="140">
			<input name="Login1:UserPass" type="password" id="Login1_UserPass"></td>
		<td>
			
			</td>
	</tr>
	<tr>
		<td></td>
		<td width="140">
			<input id="Login1_CheckBoxRememberMe" type="checkbox" name="Login1:CheckBoxRememberMe" checked="checked"><label for="Login1_CheckBoxRememberMe">Remember me</label></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>&nbsp;</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td width="140" nowrap="">
			<input type="submit" name="Login1:LoginBtn" value="Sign in" onclick="if (typeof(Page_ClientValidate) == &#39;function&#39;) Page_ClientValidate(); " language="javascript" id="Login1_LoginBtn">&nbsp;<input onclick="window.history.back(); return false" type="button" value="Cancel"></td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td>&nbsp;</td>
		<td></td>
	</tr>
	<tr>
		<td></td>
		<td width="140">
			<a id="Login1_LinkButtonResetPassword" href="javascript:__doPostBack(&#39;Login1$LinkButtonResetPassword&#39;,&#39;&#39;)">Reset password</a></td>
		<td>
			
			<input name="Login1:hiddenEmail" id="Login1_hiddenEmail" type="hidden" value="An email with instructions has been sent to {0}"></td>
	</tr>
</tbody></table>
<script>
function signUp() {
	window.location = "New.aspx" + window.location.search; 
	return false;
}
</script>
<script for="window" event="onload">
Form1.Login1_UserName.focus();
</script>
</p>
						</td>
					</tr>
				</tbody></table>
			</div>
		</form>
	


</body></html>
